name: ❓ Question/Help
description: Ask a question or get help with DeepSeek-R1
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Before asking a question, please check the documentation and existing issues.
  - type: textarea
    attributes:
      label: Question
      description: What do you need help with?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Category
      options:
        - Installation
        - Usage
        - Model Capabilities
        - Integration
        - Performance Optimization
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about your question here
